name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    uses: thisjustin816/reusable-workflows/.github/workflows/ps/ci.yml@main
    with:
      publish: false
