name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        shell: pwsh
        run: ./build.ps1

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: tests/testResults.xml
          github_token: ${{ github.token }}

      - name: Publish Code Coverage
        uses: 5monkeys/cobertura-action@v14
        with:
          repo_token: ${{ github.token }}
          path: tests/coverage.xml
          minimum_coverage: 75
          fail_below_threshold: false
          only_changed_files: true

      - name: publish
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run: ./publish.ps1
        env:
          PSGALLERYAPIKEY: ${{ secrets.PSGALLERYAPIKEY }}
