name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/powershell.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/powershell.yml'

  workflow_dispatch:

jobs:
  build:
    permissions:
      checks: write # Needed for publishing test results
      contents: write # Needed for tagging with the released version
      pull-requests: write # Needed for publishing test results
    uses: thisjustin816/reusable-workflows/.github/workflows/ps-ci.yml@main
    secrets: inherit
