name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        shell: pwsh
        run: ./build.ps1

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            tests/*.xml

      - name: publish
        if: github.ref == 'refs/heads/main'
        shell: pwsh
        run: ./publish.ps1
        env:
          PSGALLERYAPIKEY: ${{ secrets.PSGALLERYAPIKEY }}
