# This workflow uses actions that are not certified by GitHub.
name: PSScriptAnalyzer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 14 * * 3'
  workflow_dispatch:

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  analyze:
    uses: thisjustin816/reusable-workflows/.github/workflows/ps-scriptAnalyzer.yml@main
    secrets: inherit
